- name: install packages
  apt:
     update_cache: yes
     name:
       - cron
     state: present
  become: yes
- name: ensure cron is started and enabled on boot
  ansible.builtin.systemd:
    name: cron
    state: started
    enabled: yes
  become: yes


