- name: Install snapd
  ansible.builtin.apt:
    name: snapd
    state: present
  become: yes

- name: Install snap core
  community.general.snap:
    name: core
  become: yes

- name: Remove Certbot from apt
  ansible.builtin.apt:
    name: certbot
    state: absent
  become: yes

- name: Install Certbot via snap
  community.general.snap:
    name: certbot
    classic: true
  register: certbot_installed
  become: yes

- name: Confirm plugin containment level
  ansible.builtin.command: snap set certbot trust-plugin-with-root=ok
  when: certbot_installed
  become: yes

- name: Install Certbot Route53 plugin
  community.general.snap:
    name: certbot-dns-route53
    state: present
  become: yes
